In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
n=np.arange(4)
n

array([0, 1, 2, 3])

In [5]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [7]:
a[2]



8

In [8]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [11]:
a[:6:2] = -1000  
a[ : :-1]   

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [12]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\DELL\AppData\Local\Temp\ipykernel_5944\2421933163.py:2: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))


In [14]:
def f(x,y):
    return 10*x+y


b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [15]:
b[2,3]

23

In [18]:
b[0:5, 2]


array([ 2, 12, 22, 32, 42])

In [19]:
b[0:4,2]

array([ 2, 12, 22, 32])

In [20]:
b[2:5,3]

array([23, 33, 43])

In [21]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [22]:
b[1:3, : ] 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [23]:
c = np.array( [[[  0,  1,  2],            
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [24]:
c.shape

(2, 2, 3)

In [25]:
c[1,...]  

array([[100, 101, 102],
       [110, 112, 113]])

In [27]:
c[...,2]  

array([[  2,  13],
       [102, 113]])

In [30]:
c[:,:,1]

array([[  1,  12],
       [101, 112]])

In [32]:
import numpy as np 
a = np.arange(6)
a


array([0, 1, 2, 3, 4, 5])

In [34]:
 id(a)

2627108872784

In [35]:
b = a 

In [36]:
b

array([0, 1, 2, 3, 4, 5])

In [37]:
id(b)

2627108872784

In [38]:
b.shape = 3,2

In [39]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])