In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,4,5],[5,6,7],[7,8,0]])
result_dot=np.dot(a,b)
print(result_dot)


[[ 33  40  19]
 [ 75  94  55]
 [117 148  91]]


In [4]:
#transpose
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a_transpose=a.T
print(a_transpose)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
#determinant
import numpy as  np
a=([[1,2,3],[4,5,6],[7,8,9]])
det_a=np.linalg.det(a)
det_a


-9.51619735392994e-16

In [ ]:
# 