In [1]:
import numpy as np


In [4]:
a=np.array([1,2,3])
b=np.arange(3)
c = a-b
print(c)

[1 1 1]


In [5]:
print(b**2)

[0 1 4]


In [6]:
print(10*np.sin(a))

[8.41470985 9.09297427 1.41120008]


In [7]:
np.add(a,b)

array([1, 3, 5])

In [8]:
print(np.add(a,b))

[1 3 5]


In [9]:

np.subtract(a,b)

array([1, 1, 1])

In [10]:

np.multiply(a,b)

array([0, 2, 6])

In [11]:
np.divide(a,b)

C:\Users\DELL\AppData\Local\Temp\ipykernel_20724\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([inf, 2. , 1.5])

In [13]:
#2d array
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
n = np.arange(1, 10).reshape(3, 3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
m-n

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
m**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [18]:
a=np.array([[2,4,5],[6,8,9],[9,3,4]])


In [26]:
n=np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n=np.arange(1,10).reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [27]:
n=np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
c**4
c

array([1, 1, 1])

In [30]:
c**4

array([1, 1, 1], dtype=int32)

In [31]:
n**4

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]], dtype=int32)

In [32]:
m-n

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
n=np.array([3,5,8])
n
m=np.arange(3)
m

array([0, 1, 2])

In [34]:
n=np.arange(1,4)

In [36]:
n=np.arange(3)
n

array([0, 1, 2])

In [37]:
m=np.array([1,2,3],[3,4,5],[6,7,8],[3,5,8])
m

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [39]:
m=np.array([[1,2,3],[3,4,5],[6,7,8],[3,5,8]])
m


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [3, 5, 8]])

In [46]:
 n=np.arange(1,13).reshape(4,3)
 n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])