In [2]:
import numpy as np
arr1=np.array([2,3,4])
arr2=np.array([5,6,7])
result=np.hstack((arr1,arr2))
print(result)


[2 3 4 5 6 7]


In [7]:
a=np.array([[3],[4],[5]])
b=np.array([[6],[7],[8]])
np.hstack((a,b))

array([[3, 6],
       [4, 7],
       [5, 8]])

In [10]:
j=np.array([[3],[5]])
k=np.array([[61],[45]])
np.hstack((j,k))

array([[ 3, 61],
       [ 5, 45]])

In [12]:
a=np.array((3,4,5))
n=np.array((6,7,8))
np.column_stack((a,n))

array([[3, 6],
       [4, 7],
       [5, 8]])

In [15]:
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[9,9,8],[0,9,8]])
arr3=np.array([[3,5,6],[6,9,5]])
np.vstack((arr1,arr2,arr3))

array([[1, 2, 3],
       [3, 4, 5],
       [9, 9, 8],
       [0, 9, 8],
       [3, 5, 6],
       [6, 9, 5]])